### PR TITLE
DUX-540 A simple threshold fix for transfers

### LINKED ISSUE #6475: [BUG] abnormally high value transfer in `tokens_ethereum.transfers`
### Description
- transfer happened on alchemix finance
- appears to be an internal migration of tokens across vaults
- while this value was technically transferred, it blows up the scale of the values in the `amount_usd` column
- https://etherscan.io/tx/0xb23aaecc086996f8059a0de67819b0e45d82e68c2581edf889b3177d7aa96ea6
```
select
  *
from
  tokens_ethereum.transfers
where
  tx_to = 0x303241e2b3b4aed0bb0f8623e7442368fed8faf3
  and tx_hash = 0xb23aaecc086996f8059a0de67819b0e45d82e68c2581edf889b3177d7aa96ea6
  and block_date > now() - interval '90' day
```

### Current behavior
please see description above.

### Expected behavior
introduce more opinion on these datasets and filter out transfers without true economic activity onchain.

### Impacted model(s)
```
tokens_ethereum.transfers
```

### Possible solution
we should look to filter out this tx from the dataset. however, rather than hardcoding the tx, an ideal solution may be to write a subquery to find tx's that fit this description and filter out for this tx and all potential future ones. for the subquery, think about looking for transfers with value > an amount, maybe 100 billion? even that is high, but a start.

with transfers being built in macros, this should apply cross-chain as well. in order to avoid full refresh on all chains, we can remove modified step in prod orchestration and only run affected chains (ethereum).

### PR DESCRIPTION
**Pull request by Hosuke**
### Update!
Please build spells in the proper [subproject](../dbt_subprojects/) directory. For more information, please see the main [readme](../README.md), which also links to a GH discussion with the option to ask questions.

### Contribution type
Please check the type of contribution this pull request is for:

- [ ] New spell(s)
- [ ] Adding to existing spell lineage
- [x] Bug fix #6475 

**Note:** You can safely discard any section below which doesn't apply based on selection above

---

### For new spell(s)
If you are building new spell(s), please provide the following information:

- **Spell name(s):** *schema.table_name*
- **Description:** [Detailed description of the new spell(s) and their purpose]
- **Who are the new spell(s) for?** [Internal team or general community]
- **How will the new spell(s) be used downstream?** [Description of downstream usage]
- **Implementation details:** [Information on how the spell(s) are implemented]
- **Test instructions:** [How to test the new spell(s)]
- **Related issue(s):** [Link to related issues, if any]

---

### For adding to existing spell lineage
If you are adding to an existing spell lineage, please provide the following information:

- **Description:** [Description of the changes made]

---

### For bug fixes
If you are fixing a bug, please provide the following information:

- **Description:** [Description of the bug fix]
- **Steps to reproduce:** [How to reproduce the bug]
- **Implementation details:** [Information on how the bug was fixed]
- **Test instructions:** [How to test the fix]
- **Related issue(s):** [Link to related issues, if any]

---

### Additional information
Please provide any additional information that might help us review your pull request:

- [Any additional information]

---

Thank you for your contribution!

### CODE REVIEW

File: macros/models/_sector/tokens/transfers_enrich.sql [hunk 1]
```diff
@@ -14,6 +14,7 @@ END
     , evms_info_model = null
     , transfers_start_date = '2000-01-01'
     , blockchain = null
+    , usd_amount_threshold = 1000000000 -- USD amount threshold
```
Comment (jeff-dude) [inline macros/models/_sector/tokens/transfers_enrich.sql:17]: this is currently set to 1 billion. options to set threshold and their count of rows filtered out:
- 1 billion: 530 rows
- 10 billion: 58 rows
- 100 billion: 43 rows

Comment (jeff-dude) [reply macros/models/_sector/tokens/transfers_enrich.sql:17]: not sure what the magic number should be. i'm following up with the team internally.

Comment (jeff-dude) [reply macros/models/_sector/tokens/transfers_enrich.sql:17]:
```suggestion
    , usd_amount_threshold = 25000000000 -- USD amount threshold
```

Comment (jeff-dude) [reply macros/models/_sector/tokens/transfers_enrich.sql:17]: the team landed on $25b

**Review by jeff-dude — CHANGES_REQUESTED** [review]

**Review by jeff-dude — APPROVED** [review]

**Comment by jeff-dude** [comment]
marking as `blocked` for now, as i think we should test by forcing ethereum to run. the problem is, it's v heavy, and might not finish in CI

**Comment by jeff-dude** [comment]
new request: force null rather than filter out transfer events. i pushed changes for this.

**Comment by jeff-dude** [comment]
unit test output -- outputs null, as expected:
image

**Review by jeff-dude — APPROVED** [review]
